language: python

python:
  - "3.6"

install:
  - 'pip install coverage'
  - 'pip install pipenv'
  - 'pipenv install'

script:
  - 'coverage run -m unittest test_*'

after_success:
  - 'coverage xml'
  - 'bash <(curl -s https://codecov.io/bash)'
